version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017

  client:
    build:
      context: ./client
    ports:
      - 5173:5173
    depends_on:
      - mongodb
      - server

  server:
    build:
      context: ./server
    ports:
      - 8080:8080
    depends_on:
      - mongodb

volumes:
  mongodb_data:
